#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/fcd6aab3-5ee2-469a-9b9d-a4c8090e6d5d/ # 
title: cmsapi-demo
/customers:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {"message": "working"}